package com.ry.pojo;

public class BGoodsWithBLOBs extends BGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.goodsInfo
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String goodsinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.goodsInfo
     *
     * @return the value of b_goods.goodsInfo
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getGoodsinfo() {
        return goodsinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.goodsInfo
     *
     * @param goodsinfo the value for b_goods.goodsInfo
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setGoodsinfo(String goodsinfo) {
        this.goodsinfo = goodsinfo == null ? null : goodsinfo.trim();
    }
}