package com.ry.pojo;

public class ViewAddr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_addr.provenceid
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    private Integer provenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_addr.provenceName
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    private String provencename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_addr.cityid
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    private Integer cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_addr.cityname
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_addr.xName
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    private String xname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_addr.xCode
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    private Integer xcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_addr.provenceid
     *
     * @return the value of view_addr.provenceid
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public Integer getProvenceid() {
        return provenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_addr.provenceid
     *
     * @param provenceid the value for view_addr.provenceid
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public void setProvenceid(Integer provenceid) {
        this.provenceid = provenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_addr.provenceName
     *
     * @return the value of view_addr.provenceName
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public String getProvencename() {
        return provencename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_addr.provenceName
     *
     * @param provencename the value for view_addr.provenceName
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public void setProvencename(String provencename) {
        this.provencename = provencename == null ? null : provencename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_addr.cityid
     *
     * @return the value of view_addr.cityid
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_addr.cityid
     *
     * @param cityid the value for view_addr.cityid
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_addr.cityname
     *
     * @return the value of view_addr.cityname
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_addr.cityname
     *
     * @param cityname the value for view_addr.cityname
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_addr.xName
     *
     * @return the value of view_addr.xName
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public String getXname() {
        return xname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_addr.xName
     *
     * @param xname the value for view_addr.xName
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public void setXname(String xname) {
        this.xname = xname == null ? null : xname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_addr.xCode
     *
     * @return the value of view_addr.xCode
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public Integer getXcode() {
        return xcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_addr.xCode
     *
     * @param xcode the value for view_addr.xCode
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    public void setXcode(Integer xcode) {
        this.xcode = xcode;
    }
}