package com.ry.pojo;

public class BTjgoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tjgoods.id
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tjgoods.id
     *
     * @return the value of b_tjgoods.id
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tjgoods.id
     *
     * @param id the value for b_tjgoods.id
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}