package com.ry.pojo;

public class BFloorgoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_floorgoods.ID
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_floorgoods.goodsId
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_floorgoods.flag
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_floorgoods.ID
     *
     * @return the value of b_floorgoods.ID
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_floorgoods.ID
     *
     * @param id the value for b_floorgoods.ID
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_floorgoods.goodsId
     *
     * @return the value of b_floorgoods.goodsId
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_floorgoods.goodsId
     *
     * @param goodsid the value for b_floorgoods.goodsId
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_floorgoods.flag
     *
     * @return the value of b_floorgoods.flag
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_floorgoods.flag
     *
     * @param flag the value for b_floorgoods.flag
     *
     * @mbg.generated Wed Dec 25 17:17:08 GMT+08:00 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}