package com.ry.mapper;

import com.ry.dto.BTjgoodsDto;
import com.ry.pojo.BTjgoods;
import com.ry.pojo.BTjgoodsExample;
import com.ry.pojo.BTjgoodsKey;
import com.ry.pojo.BTjgoodsWithBLOBs;
import com.ry.dto.BTjgoodsDto;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BTjgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    long countByExample(BTjgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    int deleteByExample(BTjgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */


    int deleteByPrimaryKey(BTjgoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    int insert(BTjgoodsWithBLOBs record);

    
    
    int deleteByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    int insertSelective(BTjgoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    List<BTjgoodsWithBLOBs> selectByExampleWithBLOBs(BTjgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    List<BTjgoods> selectByExample(BTjgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */


    BTjgoodsWithBLOBs selectByPrimaryKey(BTjgoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    BTjgoods selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") BTjgoodsWithBLOBs record, @Param("example") BTjgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BTjgoodsWithBLOBs record, @Param("example") BTjgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
    int updateByExample(@Param("record") BTjgoods record, @Param("example") BTjgoodsExample example);


/**/
	Integer updateTjGoods(BTjgoodsDto goods);
	
	Integer insertQuickPro(BTjgoodsDto tjgoodsdto);
	
	Integer updateTjGoodsEnddate(BTjgoodsDto tjgoodsdto);
    Integer updateTjGoodsPri(BTjgoodsDto tjgoodsdto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(BTjgoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(BTjgoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:29:22 GMT+08:00 2019
     */
    int updateByPrimaryKey(BTjgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 15:23:13 CST 2019
     */
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_tjgoods
     *
     * @mbg.generated Thu Dec 26 23:39:57 CST 2019
     */
  

    /**
     * 查询参加活动的商品信息
     * @param bTjgoodsDto
     * @return
     */
	List<BTjgoodsDto> selectactivitiesByPage(BTjgoodsDto bTjgoodsDto);

	/**
	 * 显示对应活动的相关信息，用来修改
	 * @param id
	 */
	BTjgoodsDto selectActivitiesInfoById(Integer id);

	/**
	 * 修改活动
	 * @param bTjgoodsDto
	 */
	void updateActivitiesById(BTjgoodsWithBLOBs bTjgoodsWithBLOBs);
   //通过商品id查对应的闪购商品截止时间
	BTjgoodsDto selectQuickGoodsByGoodsid(BTjgoodsDto bjdto);

	/**返回团购闪购等活动商品信息
	 * @param status
	 * @return
	 */
	List<BTjgoodsDto> selectActGoods(Integer type);

	/**
	 * 查询活动信息
	 * @return
	 */
	List<BTjgoodsDto> selectactivities();

	/**
	 * 根据id查询对应活动
	 * @param activitiesId
	 */
	BTjgoodsDto selectactivityById(Integer activitiesId);

}