package com.ry.pojo;

public class BComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.ID
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.goodsId
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.cusId
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.createDate
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.level
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.commentwl
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private String commentwl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.level_sell
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private Integer levelSell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.level_wl
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    private Integer levelWl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.ID
     *
     * @return the value of b_comment.ID
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.ID
     *
     * @param id the value for b_comment.ID
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.goodsId
     *
     * @return the value of b_comment.goodsId
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.goodsId
     *
     * @param goodsid the value for b_comment.goodsId
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.cusId
     *
     * @return the value of b_comment.cusId
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.cusId
     *
     * @param cusid the value for b_comment.cusId
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.comment
     *
     * @return the value of b_comment.comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.comment
     *
     * @param comment the value for b_comment.comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.createDate
     *
     * @return the value of b_comment.createDate
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.createDate
     *
     * @param createdate the value for b_comment.createDate
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.level
     *
     * @return the value of b_comment.level
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.level
     *
     * @param level the value for b_comment.level
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.commentwl
     *
     * @return the value of b_comment.commentwl
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public String getCommentwl() {
        return commentwl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.commentwl
     *
     * @param commentwl the value for b_comment.commentwl
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setCommentwl(String commentwl) {
        this.commentwl = commentwl == null ? null : commentwl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.level_sell
     *
     * @return the value of b_comment.level_sell
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Integer getLevelSell() {
        return levelSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.level_sell
     *
     * @param levelSell the value for b_comment.level_sell
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setLevelSell(Integer levelSell) {
        this.levelSell = levelSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.level_wl
     *
     * @return the value of b_comment.level_wl
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Integer getLevelWl() {
        return levelWl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.level_wl
     *
     * @param levelWl the value for b_comment.level_wl
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setLevelWl(Integer levelWl) {
        this.levelWl = levelWl;
    }
}