package com.ry.mapper;

import com.ry.pojo.BGoodstaste2;
import com.ry.pojo.BGoodstaste2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BGoodstaste2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    long countByExample(BGoodstaste2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    int deleteByExample(BGoodstaste2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    int insert(BGoodstaste2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    int insertSelective(BGoodstaste2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    List<BGoodstaste2> selectByExample(BGoodstaste2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") BGoodstaste2 record, @Param("example") BGoodstaste2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodstaste2
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    int updateByExample(@Param("record") BGoodstaste2 record, @Param("example") BGoodstaste2Example example);

	//显示所有商品包装
    List<BGoodstaste2> selectPackageByGoodsid(Integer goodsid);
}