package com.ry.pojo;

public class BMessage extends BMessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_message.typeId
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_message.titile
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    private String titile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_message.typeId
     *
     * @return the value of b_message.typeId
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_message.typeId
     *
     * @param typeid the value for b_message.typeId
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_message.titile
     *
     * @return the value of b_message.titile
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public String getTitile() {
        return titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_message.titile
     *
     * @param titile the value for b_message.titile
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public void setTitile(String titile) {
        this.titile = titile == null ? null : titile.trim();
    }
}