package com.ry.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ry.pojo.ViewAddr;
import com.ry.pojo.ViewAddrExample;

public interface ViewAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    long countByExample(ViewAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    int deleteByExample(ViewAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    int insert(ViewAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    int insertSelective(ViewAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    List<ViewAddr> selectByExample(ViewAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") ViewAddr record, @Param("example") ViewAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_addr
     *
     * @mbg.generated Wed Dec 25 13:54:15 CST 2019
     */
    int updateByExample(@Param("record") ViewAddr record, @Param("example") ViewAddrExample example);
    
    List<ViewAddr> selectByprovice();
    
    List<ViewAddr> selectBycity(Integer id);
    
    List<ViewAddr> selectByCode(Integer id);
}