package com.ry.pojo;

public class BCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.ID
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.cusId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.goodsId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.num
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.createDate
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.tasteId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private Integer tasteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_cart.packageId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    private Integer packageid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.ID
     *
     * @return the value of b_cart.ID
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.ID
     *
     * @param id the value for b_cart.ID
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.cusId
     *
     * @return the value of b_cart.cusId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.cusId
     *
     * @param cusid the value for b_cart.cusId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.goodsId
     *
     * @return the value of b_cart.goodsId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.goodsId
     *
     * @param goodsid the value for b_cart.goodsId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.num
     *
     * @return the value of b_cart.num
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.num
     *
     * @param num the value for b_cart.num
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.createDate
     *
     * @return the value of b_cart.createDate
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.createDate
     *
     * @param createdate the value for b_cart.createDate
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.tasteId
     *
     * @return the value of b_cart.tasteId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public Integer getTasteid() {
        return tasteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.tasteId
     *
     * @param tasteid the value for b_cart.tasteId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setTasteid(Integer tasteid) {
        this.tasteid = tasteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_cart.packageId
     *
     * @return the value of b_cart.packageId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public Integer getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_cart.packageId
     *
     * @param packageid the value for b_cart.packageId
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    public void setPackageid(Integer packageid) {
        this.packageid = packageid;
    }
}