package com.ry.pojo;

import java.util.ArrayList;
import java.util.List;

public class BCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public BCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNull() {
            addCriterion("goodsId is null");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNotNull() {
            addCriterion("goodsId is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsidEqualTo(Integer value) {
            addCriterion("goodsId =", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotEqualTo(Integer value) {
            addCriterion("goodsId <>", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThan(Integer value) {
            addCriterion("goodsId >", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsId >=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThan(Integer value) {
            addCriterion("goodsId <", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThanOrEqualTo(Integer value) {
            addCriterion("goodsId <=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidIn(List<Integer> values) {
            addCriterion("goodsId in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotIn(List<Integer> values) {
            addCriterion("goodsId not in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidBetween(Integer value1, Integer value2) {
            addCriterion("goodsId between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsId not between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andCusidIsNull() {
            addCriterion("cusId is null");
            return (Criteria) this;
        }

        public Criteria andCusidIsNotNull() {
            addCriterion("cusId is not null");
            return (Criteria) this;
        }

        public Criteria andCusidEqualTo(Integer value) {
            addCriterion("cusId =", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidNotEqualTo(Integer value) {
            addCriterion("cusId <>", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidGreaterThan(Integer value) {
            addCriterion("cusId >", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cusId >=", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidLessThan(Integer value) {
            addCriterion("cusId <", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidLessThanOrEqualTo(Integer value) {
            addCriterion("cusId <=", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidIn(List<Integer> values) {
            addCriterion("cusId in", values, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidNotIn(List<Integer> values) {
            addCriterion("cusId not in", values, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidBetween(Integer value1, Integer value2) {
            addCriterion("cusId between", value1, value2, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidNotBetween(Integer value1, Integer value2) {
            addCriterion("cusId not between", value1, value2, "cusid");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(String value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(String value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(String value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(String value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(String value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLike(String value) {
            addCriterion("createDate like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotLike(String value) {
            addCriterion("createDate not like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<String> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<String> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(String value1, String value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(String value1, String value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andCommentwlIsNull() {
            addCriterion("commentwl is null");
            return (Criteria) this;
        }

        public Criteria andCommentwlIsNotNull() {
            addCriterion("commentwl is not null");
            return (Criteria) this;
        }

        public Criteria andCommentwlEqualTo(String value) {
            addCriterion("commentwl =", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlNotEqualTo(String value) {
            addCriterion("commentwl <>", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlGreaterThan(String value) {
            addCriterion("commentwl >", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlGreaterThanOrEqualTo(String value) {
            addCriterion("commentwl >=", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlLessThan(String value) {
            addCriterion("commentwl <", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlLessThanOrEqualTo(String value) {
            addCriterion("commentwl <=", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlLike(String value) {
            addCriterion("commentwl like", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlNotLike(String value) {
            addCriterion("commentwl not like", value, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlIn(List<String> values) {
            addCriterion("commentwl in", values, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlNotIn(List<String> values) {
            addCriterion("commentwl not in", values, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlBetween(String value1, String value2) {
            addCriterion("commentwl between", value1, value2, "commentwl");
            return (Criteria) this;
        }

        public Criteria andCommentwlNotBetween(String value1, String value2) {
            addCriterion("commentwl not between", value1, value2, "commentwl");
            return (Criteria) this;
        }

        public Criteria andLevelSellIsNull() {
            addCriterion("level_sell is null");
            return (Criteria) this;
        }

        public Criteria andLevelSellIsNotNull() {
            addCriterion("level_sell is not null");
            return (Criteria) this;
        }

        public Criteria andLevelSellEqualTo(Integer value) {
            addCriterion("level_sell =", value, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellNotEqualTo(Integer value) {
            addCriterion("level_sell <>", value, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellGreaterThan(Integer value) {
            addCriterion("level_sell >", value, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_sell >=", value, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellLessThan(Integer value) {
            addCriterion("level_sell <", value, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellLessThanOrEqualTo(Integer value) {
            addCriterion("level_sell <=", value, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellIn(List<Integer> values) {
            addCriterion("level_sell in", values, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellNotIn(List<Integer> values) {
            addCriterion("level_sell not in", values, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellBetween(Integer value1, Integer value2) {
            addCriterion("level_sell between", value1, value2, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelSellNotBetween(Integer value1, Integer value2) {
            addCriterion("level_sell not between", value1, value2, "levelSell");
            return (Criteria) this;
        }

        public Criteria andLevelWlIsNull() {
            addCriterion("level_wl is null");
            return (Criteria) this;
        }

        public Criteria andLevelWlIsNotNull() {
            addCriterion("level_wl is not null");
            return (Criteria) this;
        }

        public Criteria andLevelWlEqualTo(Integer value) {
            addCriterion("level_wl =", value, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlNotEqualTo(Integer value) {
            addCriterion("level_wl <>", value, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlGreaterThan(Integer value) {
            addCriterion("level_wl >", value, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_wl >=", value, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlLessThan(Integer value) {
            addCriterion("level_wl <", value, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlLessThanOrEqualTo(Integer value) {
            addCriterion("level_wl <=", value, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlIn(List<Integer> values) {
            addCriterion("level_wl in", values, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlNotIn(List<Integer> values) {
            addCriterion("level_wl not in", values, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlBetween(Integer value1, Integer value2) {
            addCriterion("level_wl between", value1, value2, "levelWl");
            return (Criteria) this;
        }

        public Criteria andLevelWlNotBetween(Integer value1, Integer value2) {
            addCriterion("level_wl not between", value1, value2, "levelWl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_comment
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}