package com.ry.pojo;

public class BMessageWithBLOBs extends BMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_message.content
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_message.content
     *
     * @return the value of b_message.content
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_message.content
     *
     * @param content the value for b_message.content
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}