package com.ry.mapper;

import com.ry.dto.CommentDto;
import com.ry.dto.CommentDto2;
import com.ry.pojo.BComment;
import com.ry.pojo.BCommentExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    Integer countByExample(BCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int deleteByExample(BCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int insert(BComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int insertSelective(BComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    List<BComment> selectByExample(BCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    BComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") BComment record, @Param("example") BCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int updateByExample(@Param("record") BComment record, @Param("example") BCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(BComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated Mon Dec 23 16:02:17 GMT+08:00 2019
     */
    int updateByPrimaryKey(BComment record);
    //分页显示评论信息
    List<CommentDto> selectCommentByPage(BComment comment);
    //批量删除
    int deleteCommentByIds(Integer[] ids);
    //查询好评/差评/中评的数量
	int selectBMBcount(Map map);
	/**
	 * 查询该商品的所有评论以及用户的头像
	 * @param id
	 * @return
	 */
	List<CommentDto> selectCommentAndCusotmer(Integer id);
	List<CommentDto2> selectAll();
}