package com.ry.pojo;

public class BOrdermain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.ID
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.orderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.cusId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.addressId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.totalCount
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String totalcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.createDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.status
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.fkDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String fkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.fhDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String fhdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.shDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String shdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.pjDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String pjdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.wxOrderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String wxorderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.zfbOrderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String zfborderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.wlId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer wlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_ordermain.wlNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String wlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.ID
     *
     * @return the value of b_ordermain.ID
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.ID
     *
     * @param id the value for b_ordermain.ID
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.orderNo
     *
     * @return the value of b_ordermain.orderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.orderNo
     *
     * @param orderno the value for b_ordermain.orderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.cusId
     *
     * @return the value of b_ordermain.cusId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.cusId
     *
     * @param cusid the value for b_ordermain.cusId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.addressId
     *
     * @return the value of b_ordermain.addressId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.addressId
     *
     * @param addressid the value for b_ordermain.addressId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.totalCount
     *
     * @return the value of b_ordermain.totalCount
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.totalCount
     *
     * @param totalcount the value for b_ordermain.totalCount
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setTotalcount(String totalcount) {
        this.totalcount = totalcount == null ? null : totalcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.createDate
     *
     * @return the value of b_ordermain.createDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.createDate
     *
     * @param createdate the value for b_ordermain.createDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.status
     *
     * @return the value of b_ordermain.status
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.status
     *
     * @param status the value for b_ordermain.status
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.fkDate
     *
     * @return the value of b_ordermain.fkDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getFkdate() {
        return fkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.fkDate
     *
     * @param fkdate the value for b_ordermain.fkDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setFkdate(String fkdate) {
        this.fkdate = fkdate == null ? null : fkdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.fhDate
     *
     * @return the value of b_ordermain.fhDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getFhdate() {
        return fhdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.fhDate
     *
     * @param fhdate the value for b_ordermain.fhDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setFhdate(String fhdate) {
        this.fhdate = fhdate == null ? null : fhdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.shDate
     *
     * @return the value of b_ordermain.shDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getShdate() {
        return shdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.shDate
     *
     * @param shdate the value for b_ordermain.shDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setShdate(String shdate) {
        this.shdate = shdate == null ? null : shdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.pjDate
     *
     * @return the value of b_ordermain.pjDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getPjdate() {
        return pjdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.pjDate
     *
     * @param pjdate the value for b_ordermain.pjDate
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setPjdate(String pjdate) {
        this.pjdate = pjdate == null ? null : pjdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.wxOrderNo
     *
     * @return the value of b_ordermain.wxOrderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getWxorderno() {
        return wxorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.wxOrderNo
     *
     * @param wxorderno the value for b_ordermain.wxOrderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setWxorderno(String wxorderno) {
        this.wxorderno = wxorderno == null ? null : wxorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.zfbOrderNo
     *
     * @return the value of b_ordermain.zfbOrderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getZfborderno() {
        return zfborderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.zfbOrderNo
     *
     * @param zfborderno the value for b_ordermain.zfbOrderNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setZfborderno(String zfborderno) {
        this.zfborderno = zfborderno == null ? null : zfborderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.wlId
     *
     * @return the value of b_ordermain.wlId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getWlid() {
        return wlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.wlId
     *
     * @param wlid the value for b_ordermain.wlId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setWlid(Integer wlid) {
        this.wlid = wlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_ordermain.wlNo
     *
     * @return the value of b_ordermain.wlNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getWlno() {
        return wlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_ordermain.wlNo
     *
     * @param wlno the value for b_ordermain.wlNo
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setWlno(String wlno) {
        this.wlno = wlno == null ? null : wlno.trim();
    }
    
}