package com.ry.mapper;

import com.ry.pojo.Kd;
import com.ry.pojo.KdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    long countByExample(KdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int deleteByExample(KdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int insert(Kd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int insertSelective(Kd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    List<Kd> selectByExample(KdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    Kd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Kd record, @Param("example") KdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int updateByExample(@Param("record") Kd record, @Param("example") KdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int updateByPrimaryKeySelective(Kd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd
     *
     * @mbg.generated Mon Dec 23 15:39:16 CST 2019
     */
    int updateByPrimaryKey(Kd record);
  //分页带查询
  	List<Kd> selectByPage(Kd org);
  //通过id批量删除
  	int deleteByIds(Integer[] ids);
}