package com.ry.pojo;

public class AreaData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.codeid
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    private Integer codeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.parentid
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.cityName
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    private String cityname;
    
   

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.codeid
     *
     * @return the value of area_data.codeid
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.codeid
     *
     * @param codeid the value for area_data.codeid
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.parentid
     *
     * @return the value of area_data.parentid
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.parentid
     *
     * @param parentid the value for area_data.parentid
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.cityName
     *
     * @return the value of area_data.cityName
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.cityName
     *
     * @param cityname the value for area_data.cityName
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }
}