package com.ry.pojo;

public class BAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.ID
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.cusId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.realName
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.proviceId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private Integer proviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.cityId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private Integer cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.areaId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.address
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.postCard
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private String postcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.phone
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.isDefault
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    private Integer isdefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.ID
     *
     * @return the value of b_address.ID
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.ID
     *
     * @param id the value for b_address.ID
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.cusId
     *
     * @return the value of b_address.cusId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.cusId
     *
     * @param cusid the value for b_address.cusId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.realName
     *
     * @return the value of b_address.realName
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.realName
     *
     * @param realname the value for b_address.realName
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.proviceId
     *
     * @return the value of b_address.proviceId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public Integer getProviceid() {
        return proviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.proviceId
     *
     * @param proviceid the value for b_address.proviceId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.cityId
     *
     * @return the value of b_address.cityId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public Integer getCityid() {
        return cityid;
    }

    public void setProviceid(Integer proviceid) {
		this.proviceid = proviceid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.cityId
     *
     * @param cityid the value for b_address.cityId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.areaId
     *
     * @return the value of b_address.areaId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public Integer getAreaid() {
        return areaid;
    }

    public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.areaId
     *
     * @param areaid the value for b_address.areaId
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.address
     *
     * @return the value of b_address.address
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public String getAddress() {
        return address;
    }

    public void setAreaid(Integer areaid) {
		this.areaid = areaid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.address
     *
     * @param address the value for b_address.address
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.postCard
     *
     * @return the value of b_address.postCard
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public String getPostcard() {
        return postcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.postCard
     *
     * @param postcard the value for b_address.postCard
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setPostcard(String postcard) {
        this.postcard = postcard == null ? null : postcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.phone
     *
     * @return the value of b_address.phone
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.phone
     *
     * @param phone the value for b_address.phone
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.isDefault
     *
     * @return the value of b_address.isDefault
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.isDefault
     *
     * @param isdefault the value for b_address.isDefault
     *
     * @mbg.generated Wed Dec 25 17:47:03 CST 2019
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }
}