package com.ry.pojo;

public class BCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collection.ID
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collection.cusId
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collection.goodsId
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collection.createDate
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    private String createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collection.ID
     *
     * @return the value of b_collection.ID
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collection.ID
     *
     * @param id the value for b_collection.ID
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collection.cusId
     *
     * @return the value of b_collection.cusId
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collection.cusId
     *
     * @param cusid the value for b_collection.cusId
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collection.goodsId
     *
     * @return the value of b_collection.goodsId
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collection.goodsId
     *
     * @param goodsid the value for b_collection.goodsId
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collection.createDate
     *
     * @return the value of b_collection.createDate
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public String getCreatedate() {
        return createdate;
    }
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collection.createDate
     *
     * @param createdate the value for b_collection.createDate
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }
}