package com.ry.pojo;

public class BGoodspicKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.ID
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.ID
     *
     * @return the value of b_goodspic.ID
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.ID
     *
     * @param id the value for b_goodspic.ID
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}