package com.ry.pojo;

import java.util.List;

public class BGoodstaste2 {
	List<SPackagetype> packages;
	
    public List<SPackagetype> getPackages() {
		return packages;
	}

	public void setPackages(List<SPackagetype> packages) {
		this.packages = packages;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodstaste2.id
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodstaste2.goodsId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodstaste2.packageId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    private Integer packageid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodstaste2.id
     *
     * @return the value of b_goodstaste2.id
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodstaste2.id
     *
     * @param id the value for b_goodstaste2.id
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodstaste2.goodsId
     *
     * @return the value of b_goodstaste2.goodsId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodstaste2.goodsId
     *
     * @param goodsid the value for b_goodstaste2.goodsId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodstaste2.packageId
     *
     * @return the value of b_goodstaste2.packageId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public Integer getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodstaste2.packageId
     *
     * @param packageid the value for b_goodstaste2.packageId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public void setPackageid(Integer packageid) {
        this.packageid = packageid;
    }
}