package com.ry.pojo;

import java.util.List;

public class BGoodstaste {
	List<STastetype> tastes;
	
    public List<STastetype> getTastes() {
		return tastes;
	}

	public void setTastes(List<STastetype> tastes) {
		this.tastes = tastes;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodstaste.id
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodstaste.goodsId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodstaste.tasteId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    private Integer tasteid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodstaste.id
     *
     * @return the value of b_goodstaste.id
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodstaste.id
     *
     * @param id the value for b_goodstaste.id
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodstaste.goodsId
     *
     * @return the value of b_goodstaste.goodsId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodstaste.goodsId
     *
     * @param goodsid the value for b_goodstaste.goodsId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodstaste.tasteId
     *
     * @return the value of b_goodstaste.tasteId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public Integer getTasteid() {
        return tasteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodstaste.tasteId
     *
     * @param tasteid the value for b_goodstaste.tasteId
     *
     * @mbg.generated Tue Dec 31 15:31:46 CST 2019
     */
    public void setTasteid(Integer tasteid) {
        this.tasteid = tasteid;
    }
}