package com.ry.pojo;

import java.util.List;

public class BGoods extends BGoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.goodsNo
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String goodsno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.typeId
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.goodsName
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.price
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.ckPrice
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String ckprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.weight
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.unit
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.userId
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.createDate
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.indexImg
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String indeximg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.status
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.lbPic
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String lbpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.storeNum
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private String storenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.goodsNo
     *
     * @return the value of b_goods.goodsNo
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    
    private SGoodstype goodstype;
    private SUser user;
    private List<STastetype> tastetypes;
    private List<SPackagetype> packagetypes;
    
    
    public List<STastetype> getTastetypes() {
		return tastetypes;
	}

	public void setTastetypes(List<STastetype> tastetypes) {
		this.tastetypes = tastetypes;
	}

	public List<SPackagetype> getPackagetypes() {
		return packagetypes;
	}

	public void setPackagetypes(List<SPackagetype> packagetypes) {
		this.packagetypes = packagetypes;
	}

	public SGoodstype getGoodstype() {
		return goodstype;
	}

	public void setGoodstype(SGoodstype goodstype) {
		this.goodstype = goodstype;
	}

	public SUser getUser() {
		return user;
	}

	public void setUser(SUser user) {
		this.user = user;
	}

	public String getGoodsno() {
        return goodsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.goodsNo
     *
     * @param goodsno the value for b_goods.goodsNo
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setGoodsno(String goodsno) {
        this.goodsno = goodsno == null ? null : goodsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.typeId
     *
     * @return the value of b_goods.typeId
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.typeId
     *
     * @param typeid the value for b_goods.typeId
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.goodsName
     *
     * @return the value of b_goods.goodsName
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.goodsName
     *
     * @param goodsname the value for b_goods.goodsName
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.price
     *
     * @return the value of b_goods.price
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.price
     *
     * @param price the value for b_goods.price
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.ckPrice
     *
     * @return the value of b_goods.ckPrice
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getCkprice() {
        return ckprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.ckPrice
     *
     * @param ckprice the value for b_goods.ckPrice
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setCkprice(String ckprice) {
        this.ckprice = ckprice == null ? null : ckprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.weight
     *
     * @return the value of b_goods.weight
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.weight
     *
     * @param weight the value for b_goods.weight
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.unit
     *
     * @return the value of b_goods.unit
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.unit
     *
     * @param unit the value for b_goods.unit
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.userId
     *
     * @return the value of b_goods.userId
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.userId
     *
     * @param userid the value for b_goods.userId
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.createDate
     *
     * @return the value of b_goods.createDate
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.createDate
     *
     * @param createdate the value for b_goods.createDate
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.indexImg
     *
     * @return the value of b_goods.indexImg
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getIndeximg() {
        return indeximg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.indexImg
     *
     * @param indeximg the value for b_goods.indexImg
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setIndeximg(String indeximg) {
        this.indeximg = indeximg == null ? null : indeximg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.status
     *
     * @return the value of b_goods.status
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.status
     *
     * @param status the value for b_goods.status
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.lbPic
     *
     * @return the value of b_goods.lbPic
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getLbpic() {
        return lbpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.lbPic
     *
     * @param lbpic the value for b_goods.lbPic
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setLbpic(String lbpic) {
        this.lbpic = lbpic == null ? null : lbpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.storeNum
     *
     * @return the value of b_goods.storeNum
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public String getStorenum() {
        return storenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.storeNum
     *
     * @param storenum the value for b_goods.storeNum
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setStorenum(String storenum) {
        this.storenum = storenum == null ? null : storenum.trim();
    }
}