package com.ry.pojo;

public class BGoodspic extends BGoodspicKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.goodsId
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.url
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.isFirst
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private Integer isfirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.status
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.userId
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goodspic.createDate
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    private String createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.goodsId
     *
     * @return the value of b_goodspic.goodsId
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.goodsId
     *
     * @param goodsid the value for b_goodspic.goodsId
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.url
     *
     * @return the value of b_goodspic.url
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.url
     *
     * @param url the value for b_goodspic.url
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.isFirst
     *
     * @return the value of b_goodspic.isFirst
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public Integer getIsfirst() {
        return isfirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.isFirst
     *
     * @param isfirst the value for b_goodspic.isFirst
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setIsfirst(Integer isfirst) {
        this.isfirst = isfirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.status
     *
     * @return the value of b_goodspic.status
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.status
     *
     * @param status the value for b_goodspic.status
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.userId
     *
     * @return the value of b_goodspic.userId
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.userId
     *
     * @param userid the value for b_goodspic.userId
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goodspic.createDate
     *
     * @return the value of b_goodspic.createDate
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goodspic.createDate
     *
     * @param createdate the value for b_goodspic.createDate
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }
}