package com.ry.pojo;

public class BMessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_message.ID
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_message.ID
     *
     * @return the value of b_message.ID
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_message.ID
     *
     * @param id the value for b_message.ID
     *
     * @mbg.generated Fri Dec 27 11:44:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}