package com.ry.pojo;

public class BOrderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.ID
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.mainId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer mainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.goodsId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.price
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.num
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.totalPrice
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private String totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.tastedId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer tastedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderdetail.packageId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    private Integer packageid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.ID
     *
     * @return the value of b_orderdetail.ID
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    
    /**
     * 订单详情对商品是一对一
     */
    private BGoods goods;   
    /**
     * 一个订单对应一个客户
     */
    private BCustomer customer;
    
    public BGoods getGoods() {
		return goods;
	}
	public void setGoods(BGoods goods) {
		this.goods = goods;
	}
	public Integer getId() {
        return id;
    }

    public BCustomer getCustomer() {
		return customer;
	}

	public void setCustomer(BCustomer customer) {
		this.customer = customer;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.ID
     *
     * @param id the value for b_orderdetail.ID
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.mainId
     *
     * @return the value of b_orderdetail.mainId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getMainid() {
        return mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.mainId
     *
     * @param mainid the value for b_orderdetail.mainId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setMainid(Integer mainid) {
        this.mainid = mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.goodsId
     *
     * @return the value of b_orderdetail.goodsId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.goodsId
     *
     * @param goodsid the value for b_orderdetail.goodsId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.price
     *
     * @return the value of b_orderdetail.price
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.price
     *
     * @param price the value for b_orderdetail.price
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.num
     *
     * @return the value of b_orderdetail.num
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.num
     *
     * @param num the value for b_orderdetail.num
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.totalPrice
     *
     * @return the value of b_orderdetail.totalPrice
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.totalPrice
     *
     * @param totalprice the value for b_orderdetail.totalPrice
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setTotalprice(String totalprice) {
        this.totalprice = totalprice == null ? null : totalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.tastedId
     *
     * @return the value of b_orderdetail.tastedId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getTastedid() {
        return tastedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.tastedId
     *
     * @param tastedid the value for b_orderdetail.tastedId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setTastedid(Integer tastedid) {
        this.tastedid = tastedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderdetail.packageId
     *
     * @return the value of b_orderdetail.packageId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Integer getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderdetail.packageId
     *
     * @param packageid the value for b_orderdetail.packageId
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setPackageid(Integer packageid) {
        this.packageid = packageid;
    }
}