package com.ry.pojo;

import java.util.ArrayList;
import java.util.List;

public class BOrdermainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public BOrdermainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("orderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("orderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("orderNo =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("orderNo <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("orderNo >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("orderNo >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("orderNo <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("orderNo <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("orderNo like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("orderNo not like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<String> values) {
            addCriterion("orderNo in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<String> values) {
            addCriterion("orderNo not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("orderNo between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("orderNo not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andCusidIsNull() {
            addCriterion("cusId is null");
            return (Criteria) this;
        }

        public Criteria andCusidIsNotNull() {
            addCriterion("cusId is not null");
            return (Criteria) this;
        }

        public Criteria andCusidEqualTo(Integer value) {
            addCriterion("cusId =", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidNotEqualTo(Integer value) {
            addCriterion("cusId <>", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidGreaterThan(Integer value) {
            addCriterion("cusId >", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cusId >=", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidLessThan(Integer value) {
            addCriterion("cusId <", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidLessThanOrEqualTo(Integer value) {
            addCriterion("cusId <=", value, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidIn(List<Integer> values) {
            addCriterion("cusId in", values, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidNotIn(List<Integer> values) {
            addCriterion("cusId not in", values, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidBetween(Integer value1, Integer value2) {
            addCriterion("cusId between", value1, value2, "cusid");
            return (Criteria) this;
        }

        public Criteria andCusidNotBetween(Integer value1, Integer value2) {
            addCriterion("cusId not between", value1, value2, "cusid");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNull() {
            addCriterion("addressId is null");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNotNull() {
            addCriterion("addressId is not null");
            return (Criteria) this;
        }

        public Criteria andAddressidEqualTo(Integer value) {
            addCriterion("addressId =", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotEqualTo(Integer value) {
            addCriterion("addressId <>", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThan(Integer value) {
            addCriterion("addressId >", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThanOrEqualTo(Integer value) {
            addCriterion("addressId >=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThan(Integer value) {
            addCriterion("addressId <", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThanOrEqualTo(Integer value) {
            addCriterion("addressId <=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidIn(List<Integer> values) {
            addCriterion("addressId in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotIn(List<Integer> values) {
            addCriterion("addressId not in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidBetween(Integer value1, Integer value2) {
            addCriterion("addressId between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotBetween(Integer value1, Integer value2) {
            addCriterion("addressId not between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andTotalcountIsNull() {
            addCriterion("totalCount is null");
            return (Criteria) this;
        }

        public Criteria andTotalcountIsNotNull() {
            addCriterion("totalCount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcountEqualTo(String value) {
            addCriterion("totalCount =", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotEqualTo(String value) {
            addCriterion("totalCount <>", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountGreaterThan(String value) {
            addCriterion("totalCount >", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountGreaterThanOrEqualTo(String value) {
            addCriterion("totalCount >=", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountLessThan(String value) {
            addCriterion("totalCount <", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountLessThanOrEqualTo(String value) {
            addCriterion("totalCount <=", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountLike(String value) {
            addCriterion("totalCount like", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotLike(String value) {
            addCriterion("totalCount not like", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountIn(List<String> values) {
            addCriterion("totalCount in", values, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotIn(List<String> values) {
            addCriterion("totalCount not in", values, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountBetween(String value1, String value2) {
            addCriterion("totalCount between", value1, value2, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotBetween(String value1, String value2) {
            addCriterion("totalCount not between", value1, value2, "totalcount");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(String value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(String value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(String value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(String value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(String value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLike(String value) {
            addCriterion("createDate like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotLike(String value) {
            addCriterion("createDate not like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<String> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<String> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(String value1, String value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(String value1, String value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFkdateIsNull() {
            addCriterion("fkDate is null");
            return (Criteria) this;
        }

        public Criteria andFkdateIsNotNull() {
            addCriterion("fkDate is not null");
            return (Criteria) this;
        }

        public Criteria andFkdateEqualTo(String value) {
            addCriterion("fkDate =", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateNotEqualTo(String value) {
            addCriterion("fkDate <>", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateGreaterThan(String value) {
            addCriterion("fkDate >", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateGreaterThanOrEqualTo(String value) {
            addCriterion("fkDate >=", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateLessThan(String value) {
            addCriterion("fkDate <", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateLessThanOrEqualTo(String value) {
            addCriterion("fkDate <=", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateLike(String value) {
            addCriterion("fkDate like", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateNotLike(String value) {
            addCriterion("fkDate not like", value, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateIn(List<String> values) {
            addCriterion("fkDate in", values, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateNotIn(List<String> values) {
            addCriterion("fkDate not in", values, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateBetween(String value1, String value2) {
            addCriterion("fkDate between", value1, value2, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFkdateNotBetween(String value1, String value2) {
            addCriterion("fkDate not between", value1, value2, "fkdate");
            return (Criteria) this;
        }

        public Criteria andFhdateIsNull() {
            addCriterion("fhDate is null");
            return (Criteria) this;
        }

        public Criteria andFhdateIsNotNull() {
            addCriterion("fhDate is not null");
            return (Criteria) this;
        }

        public Criteria andFhdateEqualTo(String value) {
            addCriterion("fhDate =", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateNotEqualTo(String value) {
            addCriterion("fhDate <>", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateGreaterThan(String value) {
            addCriterion("fhDate >", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateGreaterThanOrEqualTo(String value) {
            addCriterion("fhDate >=", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateLessThan(String value) {
            addCriterion("fhDate <", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateLessThanOrEqualTo(String value) {
            addCriterion("fhDate <=", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateLike(String value) {
            addCriterion("fhDate like", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateNotLike(String value) {
            addCriterion("fhDate not like", value, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateIn(List<String> values) {
            addCriterion("fhDate in", values, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateNotIn(List<String> values) {
            addCriterion("fhDate not in", values, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateBetween(String value1, String value2) {
            addCriterion("fhDate between", value1, value2, "fhdate");
            return (Criteria) this;
        }

        public Criteria andFhdateNotBetween(String value1, String value2) {
            addCriterion("fhDate not between", value1, value2, "fhdate");
            return (Criteria) this;
        }

        public Criteria andShdateIsNull() {
            addCriterion("shDate is null");
            return (Criteria) this;
        }

        public Criteria andShdateIsNotNull() {
            addCriterion("shDate is not null");
            return (Criteria) this;
        }

        public Criteria andShdateEqualTo(String value) {
            addCriterion("shDate =", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotEqualTo(String value) {
            addCriterion("shDate <>", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateGreaterThan(String value) {
            addCriterion("shDate >", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateGreaterThanOrEqualTo(String value) {
            addCriterion("shDate >=", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateLessThan(String value) {
            addCriterion("shDate <", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateLessThanOrEqualTo(String value) {
            addCriterion("shDate <=", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateLike(String value) {
            addCriterion("shDate like", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotLike(String value) {
            addCriterion("shDate not like", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateIn(List<String> values) {
            addCriterion("shDate in", values, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotIn(List<String> values) {
            addCriterion("shDate not in", values, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateBetween(String value1, String value2) {
            addCriterion("shDate between", value1, value2, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotBetween(String value1, String value2) {
            addCriterion("shDate not between", value1, value2, "shdate");
            return (Criteria) this;
        }

        public Criteria andPjdateIsNull() {
            addCriterion("pjDate is null");
            return (Criteria) this;
        }

        public Criteria andPjdateIsNotNull() {
            addCriterion("pjDate is not null");
            return (Criteria) this;
        }

        public Criteria andPjdateEqualTo(String value) {
            addCriterion("pjDate =", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateNotEqualTo(String value) {
            addCriterion("pjDate <>", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateGreaterThan(String value) {
            addCriterion("pjDate >", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateGreaterThanOrEqualTo(String value) {
            addCriterion("pjDate >=", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateLessThan(String value) {
            addCriterion("pjDate <", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateLessThanOrEqualTo(String value) {
            addCriterion("pjDate <=", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateLike(String value) {
            addCriterion("pjDate like", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateNotLike(String value) {
            addCriterion("pjDate not like", value, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateIn(List<String> values) {
            addCriterion("pjDate in", values, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateNotIn(List<String> values) {
            addCriterion("pjDate not in", values, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateBetween(String value1, String value2) {
            addCriterion("pjDate between", value1, value2, "pjdate");
            return (Criteria) this;
        }

        public Criteria andPjdateNotBetween(String value1, String value2) {
            addCriterion("pjDate not between", value1, value2, "pjdate");
            return (Criteria) this;
        }

        public Criteria andWxordernoIsNull() {
            addCriterion("wxOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andWxordernoIsNotNull() {
            addCriterion("wxOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andWxordernoEqualTo(String value) {
            addCriterion("wxOrderNo =", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoNotEqualTo(String value) {
            addCriterion("wxOrderNo <>", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoGreaterThan(String value) {
            addCriterion("wxOrderNo >", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoGreaterThanOrEqualTo(String value) {
            addCriterion("wxOrderNo >=", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoLessThan(String value) {
            addCriterion("wxOrderNo <", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoLessThanOrEqualTo(String value) {
            addCriterion("wxOrderNo <=", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoLike(String value) {
            addCriterion("wxOrderNo like", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoNotLike(String value) {
            addCriterion("wxOrderNo not like", value, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoIn(List<String> values) {
            addCriterion("wxOrderNo in", values, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoNotIn(List<String> values) {
            addCriterion("wxOrderNo not in", values, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoBetween(String value1, String value2) {
            addCriterion("wxOrderNo between", value1, value2, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andWxordernoNotBetween(String value1, String value2) {
            addCriterion("wxOrderNo not between", value1, value2, "wxorderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoIsNull() {
            addCriterion("zfbOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andZfbordernoIsNotNull() {
            addCriterion("zfbOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andZfbordernoEqualTo(String value) {
            addCriterion("zfbOrderNo =", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoNotEqualTo(String value) {
            addCriterion("zfbOrderNo <>", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoGreaterThan(String value) {
            addCriterion("zfbOrderNo >", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoGreaterThanOrEqualTo(String value) {
            addCriterion("zfbOrderNo >=", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoLessThan(String value) {
            addCriterion("zfbOrderNo <", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoLessThanOrEqualTo(String value) {
            addCriterion("zfbOrderNo <=", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoLike(String value) {
            addCriterion("zfbOrderNo like", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoNotLike(String value) {
            addCriterion("zfbOrderNo not like", value, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoIn(List<String> values) {
            addCriterion("zfbOrderNo in", values, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoNotIn(List<String> values) {
            addCriterion("zfbOrderNo not in", values, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoBetween(String value1, String value2) {
            addCriterion("zfbOrderNo between", value1, value2, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andZfbordernoNotBetween(String value1, String value2) {
            addCriterion("zfbOrderNo not between", value1, value2, "zfborderno");
            return (Criteria) this;
        }

        public Criteria andWlidIsNull() {
            addCriterion("wlId is null");
            return (Criteria) this;
        }

        public Criteria andWlidIsNotNull() {
            addCriterion("wlId is not null");
            return (Criteria) this;
        }

        public Criteria andWlidEqualTo(Integer value) {
            addCriterion("wlId =", value, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidNotEqualTo(Integer value) {
            addCriterion("wlId <>", value, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidGreaterThan(Integer value) {
            addCriterion("wlId >", value, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wlId >=", value, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidLessThan(Integer value) {
            addCriterion("wlId <", value, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidLessThanOrEqualTo(Integer value) {
            addCriterion("wlId <=", value, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidIn(List<Integer> values) {
            addCriterion("wlId in", values, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidNotIn(List<Integer> values) {
            addCriterion("wlId not in", values, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidBetween(Integer value1, Integer value2) {
            addCriterion("wlId between", value1, value2, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlidNotBetween(Integer value1, Integer value2) {
            addCriterion("wlId not between", value1, value2, "wlid");
            return (Criteria) this;
        }

        public Criteria andWlnoIsNull() {
            addCriterion("wlNo is null");
            return (Criteria) this;
        }

        public Criteria andWlnoIsNotNull() {
            addCriterion("wlNo is not null");
            return (Criteria) this;
        }

        public Criteria andWlnoEqualTo(String value) {
            addCriterion("wlNo =", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoNotEqualTo(String value) {
            addCriterion("wlNo <>", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoGreaterThan(String value) {
            addCriterion("wlNo >", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoGreaterThanOrEqualTo(String value) {
            addCriterion("wlNo >=", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoLessThan(String value) {
            addCriterion("wlNo <", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoLessThanOrEqualTo(String value) {
            addCriterion("wlNo <=", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoLike(String value) {
            addCriterion("wlNo like", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoNotLike(String value) {
            addCriterion("wlNo not like", value, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoIn(List<String> values) {
            addCriterion("wlNo in", values, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoNotIn(List<String> values) {
            addCriterion("wlNo not in", values, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoBetween(String value1, String value2) {
            addCriterion("wlNo between", value1, value2, "wlno");
            return (Criteria) this;
        }

        public Criteria andWlnoNotBetween(String value1, String value2) {
            addCriterion("wlNo not between", value1, value2, "wlno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_ordermain
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 23 15:07:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_ordermain
     *
     * @mbg.generated Mon Dec 23 15:07:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}