package com.ry.pojo;

public class BSlidegoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_slidegoods.ID
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_slidegoods.goodsId
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_slidegoods.status
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_slidegoods.ID
     *
     * @return the value of b_slidegoods.ID
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_slidegoods.ID
     *
     * @param id the value for b_slidegoods.ID
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_slidegoods.goodsId
     *
     * @return the value of b_slidegoods.goodsId
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_slidegoods.goodsId
     *
     * @param goodsid the value for b_slidegoods.goodsId
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_slidegoods.status
     *
     * @return the value of b_slidegoods.status
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_slidegoods.status
     *
     * @param status the value for b_slidegoods.status
     *
     * @mbg.generated Sat Dec 28 16:26:32 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}