package com.ry.pojo;

public class BTjgoodsWithBLOBs extends BTjgoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tjgoods.context
     *
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tjgoods.context
     *
     * @return the value of b_tjgoods.context
     *
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tjgoods.context
     *
     * @param context the value for b_tjgoods.context
     *
     * @mbg.generated Wed Dec 25 10:36:35 GMT+08:00 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}