package com.ry.pojo;

public class Kd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.id
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.type
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.common
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private Integer common;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.company
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.code
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.track
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private String track;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.list
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private String list;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd.take
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    private String take;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.id
     *
     * @return the value of kd.id
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.id
     *
     * @param id the value for kd.id
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.type
     *
     * @return the value of kd.type
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.type
     *
     * @param type the value for kd.type
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.common
     *
     * @return the value of kd.common
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public Integer getCommon() {
        return common;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.common
     *
     * @param common the value for kd.common
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setCommon(Integer common) {
        this.common = common;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.company
     *
     * @return the value of kd.company
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.company
     *
     * @param company the value for kd.company
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.code
     *
     * @return the value of kd.code
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.code
     *
     * @param code the value for kd.code
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.track
     *
     * @return the value of kd.track
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public String getTrack() {
        return track;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.track
     *
     * @param track the value for kd.track
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setTrack(String track) {
        this.track = track == null ? null : track.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.list
     *
     * @return the value of kd.list
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public String getList() {
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.list
     *
     * @param list the value for kd.list
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setList(String list) {
        this.list = list == null ? null : list.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd.take
     *
     * @return the value of kd.take
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public String getTake() {
        return take;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd.take
     *
     * @param take the value for kd.take
     *
     * @mbg.generated Mon Dec 23 15:01:11 CST 2019
     */
    public void setTake(String take) {
        this.take = take == null ? null : take.trim();
    }
}