
package com.ry.pojo;

public class SGoodstype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goodstype.id
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goodstype.typeName
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goodstype.pid
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goodstype.status
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goodstype.param1
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    private String param1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goodstype.param2
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    private String param2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goodstype.id
     *
     * @return the value of s_goodstype.id
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    
    private Float rj;
    private Integer goodsFlow;
    

    private Float salesmoney;
    

	public Integer getGoodsFlow() {
		return goodsFlow;
	}

	public void setGoodsFlow(Integer goodsFlow) {
		this.goodsFlow = goodsFlow;
	}


	public Float getRj() {
		return rj;
	}

	public void setRj(Float rj) {
		this.rj = rj;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goodstype.id
     *
     * @param id the value for s_goodstype.id
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goodstype.typeName
     *
     * @return the value of s_goodstype.typeName
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goodstype.typeName
     *
     * @param typename the value for s_goodstype.typeName
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goodstype.pid
     *
     * @return the value of s_goodstype.pid
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goodstype.pid
     *
     * @param pid the value for s_goodstype.pid
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goodstype.status
     *
     * @return the value of s_goodstype.status
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goodstype.status
     *
     * @param status the value for s_goodstype.status
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goodstype.param1
     *
     * @return the value of s_goodstype.param1
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goodstype.param1
     *
     * @param param1 the value for s_goodstype.param1
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goodstype.param2
     *
     * @return the value of s_goodstype.param2
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goodstype.param2
     *
     * @param param2 the value for s_goodstype.param2
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

	public Float getSalesmoney() {
		return salesmoney;
	}

	public void setSalesmoney(Float salesmoney) {
		this.salesmoney = salesmoney;
	}
    
}