package com.ry.pojo;

public class SMessagetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_messagetype.id
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_messagetype.newsname
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    private String newsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_messagetype.type
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_messagetype.id
     *
     * @return the value of s_messagetype.id
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_messagetype.id
     *
     * @param id the value for s_messagetype.id
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_messagetype.newsname
     *
     * @return the value of s_messagetype.newsname
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    public String getNewsname() {
        return newsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_messagetype.newsname
     *
     * @param newsname the value for s_messagetype.newsname
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    public void setNewsname(String newsname) {
        this.newsname = newsname == null ? null : newsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_messagetype.type
     *
     * @return the value of s_messagetype.type
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_messagetype.type
     *
     * @param type the value for s_messagetype.type
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}