package com.ry.pojo;

public class SOrganization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_organization.id
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_organization.orgName
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_organization.pid
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_organization.principalId
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private Integer principalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_organization.status
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_organization.id
     *
     * @return the value of s_organization.id
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_organization.id
     *
     * @param id the value for s_organization.id
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_organization.orgName
     *
     * @return the value of s_organization.orgName
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_organization.orgName
     *
     * @param orgname the value for s_organization.orgName
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_organization.pid
     *
     * @return the value of s_organization.pid
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_organization.pid
     *
     * @param pid the value for s_organization.pid
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_organization.principalId
     *
     * @return the value of s_organization.principalId
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public Integer getPrincipalid() {
        return principalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_organization.principalId
     *
     * @param principalid the value for s_organization.principalId
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setPrincipalid(Integer principalid) {
        this.principalid = principalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_organization.status
     *
     * @return the value of s_organization.status
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_organization.status
     *
     * @param status the value for s_organization.status
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}