package com.ry.pojo;

public class SPackagetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_packagetype.id
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_packagetype.typeName
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_packagetype.status
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_packagetype.param1
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    private String param1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_packagetype.param2
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    private String param2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_packagetype.id
     *
     * @return the value of s_packagetype.id
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_packagetype.id
     *
     * @param id the value for s_packagetype.id
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_packagetype.typeName
     *
     * @return the value of s_packagetype.typeName
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_packagetype.typeName
     *
     * @param typename the value for s_packagetype.typeName
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_packagetype.status
     *
     * @return the value of s_packagetype.status
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_packagetype.status
     *
     * @param status the value for s_packagetype.status
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_packagetype.param1
     *
     * @return the value of s_packagetype.param1
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_packagetype.param1
     *
     * @param param1 the value for s_packagetype.param1
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_packagetype.param2
     *
     * @return the value of s_packagetype.param2
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_packagetype.param2
     *
     * @param param2 the value for s_packagetype.param2
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }
}