package com.ry.pojo;

public class SRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.id
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.roleName
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.status
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.id
     *
     * @return the value of s_role.id
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.id
     *
     * @param id the value for s_role.id
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.roleName
     *
     * @return the value of s_role.roleName
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.roleName
     *
     * @param rolename the value for s_role.roleName
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.status
     *
     * @return the value of s_role.status
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.status
     *
     * @param status the value for s_role.status
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}