package com.ry.pojo;

public class SResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_resource.id
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_resource.resourceName
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    private String resourcename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_resource.url
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_resource.pid
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_resource.sort
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_resource.icon
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_resource.id
     *
     * @return the value of s_resource.id
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_resource.id
     *
     * @param id the value for s_resource.id
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_resource.resourceName
     *
     * @return the value of s_resource.resourceName
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public String getResourcename() {
        return resourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_resource.resourceName
     *
     * @param resourcename the value for s_resource.resourceName
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public void setResourcename(String resourcename) {
        this.resourcename = resourcename == null ? null : resourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_resource.url
     *
     * @return the value of s_resource.url
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_resource.url
     *
     * @param url the value for s_resource.url
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_resource.pid
     *
     * @return the value of s_resource.pid
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_resource.pid
     *
     * @param pid the value for s_resource.pid
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_resource.sort
     *
     * @return the value of s_resource.sort
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_resource.sort
     *
     * @param sort the value for s_resource.sort
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_resource.icon
     *
     * @return the value of s_resource.icon
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_resource.icon
     *
     * @param icon the value for s_resource.icon
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}