package com.ry.mapper;

import com.ry.pojo.AreaData;
import com.ry.pojo.AreaDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    long countByExample(AreaDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    int deleteByExample(AreaDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    int insert(AreaData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    int insertSelective(AreaData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    List<AreaData> selectByExample(AreaDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") AreaData record, @Param("example") AreaDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbg.generated Mon Dec 23 20:01:09 GMT+08:00 2019
     */
    int updateByExample(@Param("record") AreaData record, @Param("example") AreaDataExample example);
}