package com.ry.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ry.dto.BcartGoodsDto;
import com.ry.pojo.BCart;
import com.ry.pojo.BCartExample;

public interface BCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    long countByExample(BCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int deleteByExample(BCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int insert(BCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int insertSelective(BCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    List<BCart> selectByExample(BCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    BCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") BCart record, @Param("example") BCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int updateByExample(@Param("record") BCart record, @Param("example") BCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int updateByPrimaryKeySelective(BCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_cart
     *
     * @mbg.generated Mon Dec 30 14:31:25 CST 2019
     */
    int updateByPrimaryKey(BCart record);
    /**
     * 通过用户的id来查询用户在购物车中所添加的商品
     * @param id
     * @return
     */
	List<BcartGoodsDto> selectShopCartByCusid(Integer id);
	/**
	 * 用户添加购物车时判断数据库中是否存在一样的商品属性
	 * @param bCart
	 * @return
	 */
	BCart selectWetherSame(BCart bCart);
	
	//通过购物车id查所有信息
	BcartGoodsDto selectCartByCartId(Integer cartId);
}