package com.ry.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ry.dto.CollectionDto;
import com.ry.pojo.BCollection;
import com.ry.pojo.BCollectionExample;

public interface BCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    long countByExample(BCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int deleteByExample(BCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int insert(BCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int insertSelective(BCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    List<BCollection> selectByExample(BCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    BCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") BCollection record, @Param("example") BCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int updateByExample(@Param("record") BCollection record, @Param("example") BCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int updateByPrimaryKeySelective(BCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collection
     *
     * @mbg.generated Tue Dec 31 09:27:45 CST 2019
     */
    int updateByPrimaryKey(BCollection record);

	/**根据用户id查询收藏商品
	 * @param id
	 * @return
	 */
	List<CollectionDto> selectAllCollection(Integer id);
}