package com.ry.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ry.dto.UserStatisticsDto;
import com.ry.pojo.BCustomer;
import com.ry.pojo.BCustomerExample;

public interface BCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    long countByExample(BCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int deleteByExample(BCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int insert(BCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int insertSelective(BCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    List<BCustomer> selectByExample(BCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    BCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") BCustomer record, @Param("example") BCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int updateByExample(@Param("record") BCustomer record, @Param("example") BCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int updateByPrimaryKeySelective(BCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_customer
     *
     * @mbg.generated Mon Dec 23 16:05:40 CST 2019
     */
    int updateByPrimaryKey(BCustomer record);
    
    
    
    int selectLogin(BCustomer record);

    int updatePasswordById(BCustomer bcustomer);



	/**查询时间和总计
	 * @param date
	 * @return
	 */
	List<UserStatisticsDto> selectAllCount();

	BCustomer selectLogin2(BCustomer customer);

	int selectyz(BCustomer customer);
	int selectsj(BCustomer customer);

    
}