package com.ry.mapper;

import com.ry.pojo.BGoodspic;
import com.ry.pojo.BGoodspicExample;
import com.ry.pojo.BGoodspicKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BGoodspicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    long countByExample(BGoodspicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int deleteByExample(BGoodspicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int deleteByPrimaryKey(BGoodspicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int insert(BGoodspic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int insertSelective(BGoodspic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    List<BGoodspic> selectByExample(BGoodspicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    BGoodspic selectByPrimaryKey(BGoodspicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") BGoodspic record, @Param("example") BGoodspicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int updateByExample(@Param("record") BGoodspic record, @Param("example") BGoodspicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int updateByPrimaryKeySelective(BGoodspic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_goodspic
     *
     * @mbg.generated Sat Dec 28 21:33:05 CST 2019
     */
    int updateByPrimaryKey(BGoodspic record);
}