package com.ry.mapper;

import com.ry.dto.BTjgoodsDto;
import com.ry.dto.GoodsDto;

import com.ry.dto.SGood;
import com.ry.pojo.BGoods;
import com.ry.pojo.SGoodstype;
import com.ry.pojo.SGoodstypeExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SGoodstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    long countByExample(SGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int deleteByExample(SGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int insert(SGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int insertSelective(SGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    List<SGoodstype> selectByExample(SGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    SGoodstype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") SGoodstype record, @Param("example") SGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int updateByExample(@Param("record") SGoodstype record, @Param("example") SGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int updateByPrimaryKeySelective(SGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goodstype
     *
     * @mbg.generated Tue Dec 24 12:15:25 CST 2019
     */
    int updateByPrimaryKey(SGoodstype record);
    
    //*****************************
    List<SGood> selectlb(SGood goods);
    
    List<SGoodstype> selectyj();

    
    SGood selectbl(int a);
    
    
    /*查询所有闪购商品*/
    List<BTjgoodsDto> selectAllQuickGoods(BTjgoodsDto tjDto);

	/**查询二级菜单及商品
	 * @param id
	 * @return
	 */
    List<SGood> selectTwoClass(Integer id);
    /**/
    List<BTjgoodsDto> selectTjgoodsdto(BTjgoodsDto tjDto);
    
    
	/**查询所有无活动商品
	 * @return
	 */
    List<SGood> selectAllGoods();

	/**查询二级菜单及商品
	 * @param typeid
	 * @return
	 */
	List<SGood> selectBytypeid(Map map);

	/**名字模糊查询
	 * @param goodsname
	 * @return
	 */
	List<GoodsDto> selectByGoodsName(String goodsname);
}