package com.ry.mapper;

import com.ry.pojo.SMessagetype;
import com.ry.pojo.SMessagetypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMessagetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    long countByExample(SMessagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int deleteByExample(SMessagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int insert(SMessagetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int insertSelective(SMessagetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    List<SMessagetype> selectByExample(SMessagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    SMessagetype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") SMessagetype record, @Param("example") SMessagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int updateByExample(@Param("record") SMessagetype record, @Param("example") SMessagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int updateByPrimaryKeySelective(SMessagetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_messagetype
     *
     * @mbg.generated Fri Dec 27 19:42:47 CST 2019
     */
    int updateByPrimaryKey(SMessagetype record);
    
    
    /**/
    List<SMessagetype> selectidname();
}