package com.ry.mapper;

import com.ry.pojo.SPackagetype;
import com.ry.pojo.SPackagetypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SPackagetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    long countByExample(SPackagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int deleteByExample(SPackagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int insert(SPackagetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int insertSelective(SPackagetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    List<SPackagetype> selectByExample(SPackagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    SPackagetype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") SPackagetype record, @Param("example") SPackagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int updateByExample(@Param("record") SPackagetype record, @Param("example") SPackagetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int updateByPrimaryKeySelective(SPackagetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_packagetype
     *
     * @mbg.generated Sat Dec 28 14:23:44 CST 2019
     */
    int updateByPrimaryKey(SPackagetype record);
}