package com.ry.mapper;

import com.ry.dto.LeftListDto;
import com.ry.dto.TreeNodeDto;
import com.ry.pojo.SResource;
import com.ry.pojo.SResourceExample;
import com.ry.pojo.TreeNode;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    long countByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int deleteByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int insert(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int insertSelective(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    List<SResource> selectByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    SResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") SResource record, @Param("example") SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int updateByExample(@Param("record") SResource record, @Param("example") SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int updateByPrimaryKeySelective(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Mon Dec 16 10:52:23 CST 2019
     */
    int updateByPrimaryKey(SResource record);
    
    
    
    
 List<TreeNodeDto> selectByTree();
    
    List<TreeNode> selectResource(Integer id);
    /**
     * 判断表中是否存在该资源，有就删，没有就插入
     * @param map
     * @return
     */
    int insertSroleResource(Map map);
    
    int deleteByRoleIdAndResourceId(Map map);
    
    int selectByRoleIdAndResourceId(Map map);
    
    int deleteParentAndChild(Map map);
    
    int selectChildCount(Map map);
    
    int insertParentAndChild(Map map);
    
    int hasParendPid(Map map);

	List<SResource> selectFirstMenu(Integer roleid);

	List<SResource> selectChildMenusPid(Map map);
	
	List<LeftListDto> selectByLeftList(Integer roleId);
}