package com.ry.mapper;

import com.ry.pojo.SRole;
import com.ry.pojo.SRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    long countByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int deleteByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int insert(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int insertSelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    List<SRole> selectByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    SRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByPrimaryKey(SRole record);
    
    List<SRole> selectByPage(SRole role);
}