package com.ry.mapper;

import com.ry.dto.UserDto;
import com.ry.pojo.SUser;
import com.ry.pojo.SUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    long countByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int deleteByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int insert(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int insertSelective(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    List<SUser> selectByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    SUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") SUser record, @Param("example") SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByExample(@Param("record") SUser record, @Param("example") SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByPrimaryKeySelective(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:08:22 CST 2019
     */
    int updateByPrimaryKey(SUser record);
    
    List<UserDto> selectByPage(SUser user);
    
    int selectid(String name);
    
}