package com.ry.pojo;

public class BGoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_goods.id
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_goods.id
     *
     * @return the value of b_goods.id
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_goods.id
     *
     * @param id the value for b_goods.id
     *
     * @mbg.generated Wed Dec 25 10:53:59 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}